#!/bin/bash

DATE="$(date +%D)"
dir="$(pwd)"
Session_count="$(who | wc -l)"


echo -e "Today's date is: \e[32m ${DATE} \e[0m"
echo -e "Current directory is: \e[33m ${dir} \e[0m"
echo -e "Number of active sessions: ${Session_count}"
echo -e "Script executed by: ${USER}"