#!/bin/bash

hai() {
    echo "Guru - Hai function started"
    echo "Guru - Hai function ended"
}

sample()
{
  echo "number of session opened: $(who | wc -l)"
  echo "Today date is $(date +%D)"
  echo "Avg CPU load: $(uptime | awk -F 'load average:' '{ print $2 }' | cut -d ',' -f 1)"
  
  hai
}

sample


