#!/bin/bash

hai() {
    echo "Guru - Hai function started"
    echo "Guru - Hai function ended"
}

sample()
{
  echo "Guru- Sample function started"
  echo "Guru - Sample function ended"

  hai
}

sample


