#!/bin/bash

sample()
{
  echo "Guru- Sample function started"
  echo "Guru - Sample function ended"
}

sample

echo "End of the sample function"

sample

sleep 4

echo "End of the sample function 2nd time"
